apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maestro-demo

resources:
  - ../../base

commonLabels:
  environment: demo

# Demo-specific patches
patchesStrategicMerge:
  - patches/resources.yaml

# Demo-specific replicas
replicas:
  - name: maestro-postgres
    count: 1
  - name: maestro-redis
    count: 1
  - name: maestro-prometheus
    count: 1
  - name: maestro-grafana
    count: 1
