apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - monitoring.yaml

commonLabels:
  platform: maestro
  managed-by: kustomize

namespace: maestro-platform
